---
title: "Statistics 154/254: Modern Statistical Prediction and Machine Learning"
subtitle: "UC Berkeley, Fall 2024"
listing:
  - id: schedule
    template: assets/schedule.ejs
    contents: schedule.yml
  - id: buttons
    template: assets/buttons.ejs
    contents: buttons.yml
---

::: {#buttons}
:::


## Description
<ul>
<li> Instructor: Song Mei (songmei [at] berkeley.edu) </li>
<li> Lectures: Tuesday/Thursday 9:30 am - 11:00 am. Etcheverry 3108. </li>
<li> Office Hours: Tuesday 1 pm - 3 pm. Evans 387. </li>
<li> GSI: Ruiqi Zhang (rqzhang [at] berkeley.edu) </li>
<li> Lab sessions Friday  11:00 am - 12:59 pm, Evans 334; 3:00 pm - 4:59 pm, Evans 342. </li>
<li> Office Hours: Thursday 4 pm - 6 pm; Friday 1 pm - 3 pm. Evans 428. </li>
</ul>

This course will focus on statistical/machine learning methods, data analysis/programming skills. Upon completing this course, the students are expected to be able to 1) build baseline models for real world data analysis problems; 2) implement models using programming languages; 3) draw insights/conclusions from models.

## Announcement
<ol>
<li> First class: Aug 29, 2024 (Thursday). </li>
<li> I will process the CE students during the week of Sep 9. I will prioritize CE students performing well in HW1. </li>
<li> We will use Ed (https://edstem.org/us/courses/61329) for discussions and questions.</li>
<li> Please submit HW using Gradescope (https://www.gradescope.com/courses/811006, code: YRD5EG). </li>
<li> Please find homework and lecture notes on bCourse under “Files”. </li>
<li> HW policy: There are in total 3 late days that you can use without penalty towards grade throughout the semester. After that, there will be a 10% deduction on grades of a HW for each late day. The least grade can be dropped counting towards total grades. </li>
<li> The lectures will be recorded through Course Capture. The recordings can be found on bCourse under “Media Gallery”. </li>
</ol>


## Grading
<ul>
<li> Class attendance is required.</li>
<li> Homework per two weeks. There will be 6-7 HWs.</li>
<li> In class mid-term: Oct 24. Logistics: https://docs.google.com/document/d/1VfW1isSq68IwW8TQnZF_3o_SxJ0Yy0sDzI8QVeaSSSw/edit?usp=sharing</li>
<li> Final exam date: Dec 17. Logistics: https://docs.google.com/document/d/1VfW1isSq68IwW8TQnZF_3o_SxJ0Yy0sDzI8QVeaSSSw/edit?usp=sharing</li>
<li> Final grade will be Homework × 40 % + mid-term × 25 % + final × 35 %.</li>
<li> HW policy: There are in total three late days that you can use without penalty towards grade throughout the semester. After that, there will be a 10% deduction on grades of a HW for each late day. The least grade can be dropped counting towards total grades.</li>
</ul> 


## Topics 

Basic topics:
<ul>
<li> Tasks: Regression. Classification. Dimension reduction. Clustering.</li>
<li> Algorithms: Solving linear systems. Gradient descent. Newton’s method. Power iteration for eigenvalue problems. EM algorithms.</li>
<li> Others: Kernel methods. Regularization. Sample splitting. Resampling methods. Cross validation.</li>
</ul>

Advanced topics:
<ul>
<li> Statistical learning theory and optimization theory.</li>
<li> Bagging and Boosting. Tree based models. Neural networks. Bayesian models.</li>
<li> Online learning. Bandit problems.</li>
</ul>

## Schedule

<!---
For a style similar to that of [Stat 20](https://stat20.org), modify `index.qmd` to point to `assets/{schedule-alt.ejs,buttons-alt.ejs}` and to `{schedule-alt.yml,buttons-alt.yml}` and `_quarto.yml` to point to `assets/styles-alt.scss`.
-->

::: {#schedule}
:::

